# Generated by Django 4.2.1 on 2023-05-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='controlling_app.user')),
            ],
        ),
    ]
