# Generated by Django 4.2.1 on 2023-06-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='free', max_length=10),
        ),
    ]
