# Generated by Django 4.2.1 on 2023-06-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlling_app', '0003_asset_rename_user_portfolio_user_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='free', max_length=10),
        ),
    ]
